Error: File 'X:/github.com/bohdon/maya/maya-pulse/resources/test.ui' is not valid

while executing 'C:\Users\bsayre\AppData\Local\Programs\Python\Python39\lib\site-packages\PySide2\uic -g python --from-imports X:/github.com/bohdon/maya/maya-pulse/resources/test.ui'
